name: Deploy Develop
on:
  push:
    branches:
      - develop
    paths:
      - api/**
permissions:
  actions: write
  checks: write
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout develop
        uses: actions/checkout@v3
        with:
          ref: develop
          path: develop
      - name: checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: copy files
        run: |
          mkdir -p gh-pages/docs/develop
          cp -rf develop/api/* gh-pages/docs/develop
          cd gh-pages
          git config user.name action-user
          git config user.email action@github.com
          git add .
          git commit -m "deploy develop branche"
          git push
