name: Deploy Test
on:
  push:
    branches:
      - main
    paths:
      - api/**
permissions:
  actions: write
  checks: write
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v3
        with:
          path: main
      - name: checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: copy files
        run: |
          mkdir -p gh-pages/docs/main
          cp -rf main/api/* gh-pages/docs/main
          cd gh-pages
          git config user.name action-user
          git config user.email action@github.com
          git add .
          git commit -m "action"
          git push
